language: node_js

node_js:
  - "10.9.0"

git:
  depth: 1

before_install:
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
  - sudo apt-get -qq -y update
  - sudo apt-get install -y -qq apt-transport-https
  - sudo apt-get install -y -qq azure-cli
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
  - chmod 700 get_helm.sh
  - sudo ./get_helm.sh

jobs:
  include:
    - stage: unit_test
      script:
        - npm run lint
        - npm test
        - ./node_modules/.bin/nyc report --reporter text-lcov | ./node_modules/.bin/coveralls
    - stage: build
      script:
        - docker-compose -f docker-compose.yaml build

    - stage: push_aritifact
      script:
      if: branch = master AND ( type IN (push) OR type IN (pull_request) )
      after_success:
        -  docker-compose -f docker-compose.yaml push

    - stage: functional_test
      script:
      if: branch = master AND ( type IN (push) OR type IN (pull_request) )
      after_success:
        - helm inspect wcb_dev_${TRAVIS_BUILD_NUMBER}
        - helm install wcb_dev --name wcb_dev_${TRAVIS_BRANCH}_${TRAVIS_BUILD_NUMBER}
        - helm inspect wcb_dev_${BUILD_NUMBER}

    - stage: deploy
      script:
      if: branch = master AND ( type IN (push) OR type IN (pull_request) )
      after_success:
        - helm install wcb_dev --name wcb_dev_${TRAVIS_BRANCH}_${TRAVIS_BUILD_NUMBER}
