# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  RELEASE: ''

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.16.3'
  displayName: 'Install Node.js'
- task: Npm@1
  inputs:
    command: 'install'
- script: |
    echo -n "${DEVELOPMENT_ACCESSTOKEN}" > .env
  condition: eq(variables['Build.Reason'], 'PullRequest')
- script: |
    echo -n "${STAGING_ACCESSTOKEN}" > .env
  condition: and(in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'), eq(variables.RELEASE, ''))
- script: |
    echo -n "${PRODUCTION_ACCESSTOKEN}" > .env
  condition: and(in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'), not(eq(variables.RELEASE, '')))
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'build'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run lint'
- task: Npm@1
  env:
    SERVER_PASSWORD: '$(APPLICATION_SECRET)'
  inputs:
    command: 'custom'
    customCommand: 'test'
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    buildContext: '**'
    tags: 'WCB:$(Build.BuildId)'
