version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Running Lints...
          command: make lint

  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Running Tests...
          command: make test
  
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Building Docker Image...
          command: make build
  
  release:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout 
      - setup_remote_docker
      - run:
          name: Configuring Git credentials...
          command: |
            git config user.email "moiz.nidhi+ci@gmail.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "7d:c8:37:dc:e9:4c:cd:f5:7c:2d:a4:e7:3f:5f:e2:d4"
      - run:
          name: Release to Quay and Git master
          command: make release 
      



workflows:
  version: 2
  build_release:
    jobs:
      - lint
      - test
      - build
      - release:
          requires:
            - test
            - lint
            - build
          filters:
            branches:
              only: master



