const Koa = require('koa')
require('dotenv').config()
const auth = require('koa-basic-auth')
const routes = require('./routes/routes')
const bodyParser = require('koa-bodyparser')

// End points
const teams = require('./routes/teams')
const sponsor = require('./routes/sponsor')
const participants = require('./routes/participants')
const achievement = require('./routes/achievement')
const achievements = require('./routes/achievements')
const sources = require('./routes/sources')
const causes = require('./routes/causes')
const events = require('./routes/events')
const localities = require('./routes/localities')
const records = require('./routes/records')
const commitments = require('./routes/commitments')
const notificationRegistrations = require('./routes/notificationRegistrations')

const app = new Koa()
app
  .use(auth({pass: process.env.SERVER_PASSWORD}))
  .use(bodyParser())
  .use(routes.routes())
  .use(routes.allowedMethods())
  .use(teams.routes())
  .use(teams.allowedMethods())
  .use(sponsor.routes())
  .use(sponsor.allowedMethods())
  .use(participants.routes())
  .use(participants.allowedMethods())
  .use(achievement.routes())
  .use(achievement.allowedMethods())
  .use(achievements.routes())
  .use(achievements.allowedMethods())
  .use(sources.routes())
  .use(sources.allowedMethods())
  .use(causes.routes())
  .use(causes.allowedMethods())
  .use(events.routes())
  .use(events.allowedMethods())
  .use(localities.routes())
  .use(localities.allowedMethods())
  .use(records.routes())
  .use(records.allowedMethods())
  .use(commitments.routes())
  .use(commitments.allowedMethods())
  .use(notificationRegistrations.routes())
  .use(notificationRegistrations.allowedMethods())


module.exports = app
